# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 5
  minor: 0
  patch: 2
  AssemblyVersion: $(major).$(minor).$(patch)
  NugetVersion: $(major).$(minor).$(patch)-beta

jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: ci/build.yml

  - job: package
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'windows-latest'
    dependsOn:
      build
    steps:
      - template: ci/package.yml  