# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self
        fetchDepth: 0
      - template: ci/build.yml
      - task: PowerShell@2
        displayName: 'Set GitVersion variables for package job'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "##vso[task.setvariable variable=GitVersion.SemVer;isOutput=true]$(GitVersion.SemVer)"
            Write-Host "##vso[task.setvariable variable=GitVersion.NuGetVersionV2;isOutput=true]$(GitVersion.NuGetVersionV2)"
            Write-Host "##vso[task.setvariable variable=GitVersion.AssemblySemVer;isOutput=true]$(GitVersion.AssemblySemVer)"
        name: GitVersionOutput

  - job: package
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'windows-latest'
    dependsOn:
      build
    variables:
      GitVersionSemVer: $[ dependencies.build.outputs['GitVersionOutput.GitVersion.SemVer'] ]
      GitVersionNuGet: $[ dependencies.build.outputs['GitVersionOutput.GitVersion.NuGetVersionV2'] ]
      GitVersionAssembly: $[ dependencies.build.outputs['GitVersionOutput.GitVersion.AssemblySemVer'] ]
    steps:
      - checkout: self
        fetchDepth: 0
      - template: ci/package.yml  