# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self
      - template: ci/build.yml
        
  - job: package
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    pool:
      vmImage: 'windows-latest'
    dependsOn:
      build
    steps:
      - checkout: self
        persistCredentials: true
        clean: true
      - template: ci/package.yml  
