# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true
      - template: ci/build.yml
      - task: PowerShell@2
        displayName: 'Set version variables for package job'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "##vso[task.setvariable variable=BuildVersion;isOutput=true]$(UPDATEVERSION_BUILDVERSION)"
            Write-Host "##vso[task.setvariable variable=NewVersion;isOutput=true]$(UPDATEVERSION_NEWVERSION)"
        name: VersionOutput

  - job: package
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'windows-latest'
    dependsOn:
      build
    variables:
      BuildVersion: $[ dependencies.build.outputs['VersionOutput.BuildVersion'] ]
      PackageVersion: $[ dependencies.build.outputs['VersionOutput.NewVersion'] ]
    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true
      - task: PowerShell@2
        displayName: 'Update Version for Release'
        inputs:
          filePath: 'ci/Update-Version.ps1'
          arguments: '-BuildSourceBranch "$(Build.SourceBranch)" -BuildReason "$(Build.Reason)"'
        name: UpdateVersionForRelease
      - template: ci/package.yml  
