steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'
      

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration) /p:PackageVersion=$(GitVersionNuGet)'
      packagesToPack: 'src/OSDP.Net/OSDP.Net.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish for osx-x64'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'src/Console/Console.csproj'
      arguments: '-r osx-x64 --configuration $(BuildConfiguration) /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true --self-contained true --output $(Build.ArtifactStagingDirectory)/TestConsole/osx-x64 /p:Version=$(GitVersionAssembly)'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish for win-x64'
    inputs:
      command: 'publish'
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      projects: 'src/Console/Console.csproj'
      arguments: '-r win-x64 --configuration $(BuildConfiguration) /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true --self-contained true --output $(Build.ArtifactStagingDirectory)/TestConsole/win-x64 /p:Version=$(GitVersionAssembly)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish for linux-x64'
    inputs:
      command: 'publish'
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      projects: 'src/Console/Console.csproj'
      arguments: '-r linux-x64 --configuration $(BuildConfiguration) /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true --self-contained true --output $(Build.ArtifactStagingDirectory)/TestConsole/linux-x64 /p:Version=$(GitVersionAssembly)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish for linux-arm64'
    inputs:
      command: 'publish'
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      projects: 'src/Console/Console.csproj'
      arguments: '-r linux-arm64 --configuration $(BuildConfiguration) --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true --output $(Build.ArtifactStagingDirectory)/TestConsole/linux-arm64 /p:Version=$(GitVersionAssembly)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/TestConsole'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/OSDPTestConsole.zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
